### ISSUE TITLE
Bubbles / Obstacles not appearing in one random lane during first game.

### ISSUE THREAD

**Issue by Rolson1996** [P020690F/Ducky-Dash#1]
How to recreate bug:
1)Load Applications
2)Run game
3) Move into empty lane

Consequences:
Game becomes impossible to lose in you do't change lanes after moving into empty lane.

Expected Result:
Every lane should contain obstacles fairly regularly to make player move between lanes.

Game-play Bug
Rating: 4 (Major)

**Comment by P020690F** [comment]
Issue was fixed by randomising the objects assigned lane every time they reach the bottom of the screen, instead of just on game load.
